name: Deploy API to VPS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Set deployment variables
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

          if [ "$BRANCH" = "main" ]; then
            echo "REMOTE_PATH=/var/www/astroshare.fr" >> $GITHUB_ENV
          else
            echo "REMOTE_PATH=/var/www/dev.astroshare.fr" >> $GITHUB_ENV
          fi

      - name: Deploy via SSH as root
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} << EOF
            set -e
            cd $REMOTE_PATH

            echo "ðŸ“¦ Loading NVM"
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"

            echo "ðŸ” Git Pull"
            git fetch origin
            git checkout $BRANCH
            git pull origin $BRANCH

            echo "ðŸ“¦ Node.js version"
            nvm install
            nvm use lts/jod

            echo "ðŸ“¦ Installing dependencies"
            npm install

            echo "ðŸ— Building project"
            npm run build

            echo "ðŸš€ Build successful"
          EOF